services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
      - '9229:9229' # Debug port
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/reservations.db
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - app_data:/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    command: npm run start:dev

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  rabbitmq_data:
  app_data:
